version: '3.8'

services:
  mongodb:
    image: mongo:6.0.8
    container_name: mongo_new
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root 